server:
  port: 8082

spring:
  application:
    name: gateway

  cloud:
    gateway:

      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: student-service
          uri: http://student-service:4000
          predicates:
            - Path=/students/**

        - id: course-service
          uri: http://course-service:8083
          predicates:
            - Path=/courseService{segment:.*}/**



        - id: grade-service
          uri: http://grade-service:8084
          predicates:
            - Path=/grades/**


        - id: billing-service
          uri: http://billing-service:8085
          predicates:
            - Path=/billing/**

        - id: billing-service
          uri: http://billing-service:80
          predicates:
            - Path=/billing-service/**
