server:
  port: 8082

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter

      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/auth/**

        - id: student-service
          uri: http://student-service:8082
          predicates:
            - Path=/students/**

        - id: course-service
          uri: http://course-service:8083
          predicates:
            - Path=/courses/**

        - id: grade-service
          uri: http://grade-service:8084
          predicates:
            - Path=/grades/**

        - id: billing-service
          uri: http://billing-service:8085
          predicates:
            - Path=/billing/**
